# Generated by Django 6.0.6 on 2026-06-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0004_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='uncompleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
